# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AzeredoGab 
subtitle: Leadership & Web Development
email: g.almeida.azeredo@gmail.com
description: >
  Arquitetura e Desenvolvimento de software, PHP, .NET, Javascript, Gestão de Projetos, Café, Cerveja... tem de tudo.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://azeredogab.com/" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Gabriel Azeredo'
bio: >
  Meu nome é Gabriel Azeredo, sou Coordenador de projetos na Inforce Internet Solutions. Começei a trabalhar como Web Developer à um pouco mais de 4 anos, desde então, me transformei em um apaixonado por tecnologia e novidades nesse mundo de software.
author_image: "/assets/images/perfil.jpg"
twitter_username: azeredogab
facebook_username: uuuuarruuu
facebook_fake_name: AzeredoGab
github_username:  AzeredoGabriel

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
